name: brac_arna
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: any
  flutter_svg: any
  get_storage: any
  flutter_spinkit: any
  google_fonts: any
  simple_animations: any
  dropdown_search: ^2.0.1
  sqflite: any
  flutter_offline: any
  http: any
  hive: any
  hive_flutter: any
  path_provider: any

  url_launcher: any
  syncfusion_flutter_pdfviewer: any
  uuid: any
  intl: any
  date_format: any
  flutter_share: any
  geolocator: any
  geocoding: any
  loading_overlay: any
  fl_chart: any
  getwidget: any
  connectivity_plus: any
  fluttertoast: any
#  printing: ^5.9.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.1.3
  sticky_grouped_list: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true



  assets:
    - assets/
    - assets/images/
    - assets/locales/
    - assets/place/


  fonts:
    - family: SolaimanLipi
      fonts:
        - asset: fonts/SolaimanLipi.ttf